apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-vhgq
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-symu-tenant/rhtap-demo-app/hacbs-test-project-vhgq@sha256:0c18af4e06720c6e8bd409202c893a7569c2066dc6311b508a44a65ee8900582
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
