apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-vhgq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-vhgq
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-vhgq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-vhgq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-vhgq
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-symu-tenant/rhtap-demo-app/hacbs-test-project-vhgq@sha256:0c18af4e06720c6e8bd409202c893a7569c2066dc6311b508a44a65ee8900582
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
